###Loading Data set

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mosapabdelghany/medical-insurance-cost-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'medical-insurance-cost-dataset' dataset.
Path to dataset files: /kaggle/input/medical-insurance-cost-dataset

###Reading file

In [ ]:
import pandas as pd
df=pd.read_csv('/kaggle/input/medical-insurance-cost-dataset/insurance.csv')

###Generate a full statistical summary for all numerical columns using **'df.describe()'**

###1. min cointain minimum value
###2. max contain maximum value
###3. std contain how much individual data points differ from the mean

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

###Calculating the average insurance charge

In [ ]:
df['charges'].mean()

np.float64(13270.422265141257)

###Meadian charge for insurance

In [ ]:
df['charges'].median()

9382.033

###Count of number of individuals from each geographical region

In [ ]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64