<a href="https://colab.research.google.com/github/BhavikBuchke/Pandas-Library-Python-/blob/Panda/Exploring%20Cereal%20Nutrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Install the kaggle library**

**2. Download the dataset using the Kaggle API command**

**3. Stores the local path to the downloaded files in the variable path.**

**4. Prints the stored path to the dataset files.**

In [1]:
import kagglehub
path = kagglehub.dataset_download("crawford/80-cereals")
print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/crawford/80-cereals?dataset_version_number=2...

100%|██████████| 2.24k/2.24k [00:00<00:00, 2.15MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/crawford/80-cereals/versions/2

## **Load the data into a pandas DataFrame**

In [3]:
import pandas as pd
df = pd.read_csv('/root/.cache/kagglehub/datasets/crawford/80-cereals/versions/2/cereal.csv')

## **Printing the head of Data which is first 5 rows as standard**

In [5]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

## **Printing tail of Data which is last 5 rows as standard**

In [6]:
df.tail()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

## **Finding no. of Rows and no. of Columns in dataframe**

In [8]:
df.shape

(77, 16)

## **Gathering the information about the dataframe**

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

## **Finding the name of columns in dataframe**

In [10]:
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')