<a href="https://colab.research.google.com/github/BhavikBuchke/Pandas-Library-Python-/blob/Panda/Filtering_for_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Load Black-friday sales Dataset

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("prepinstaprime/black-friday-sales-data")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/prepinstaprime/black-friday-sales-data?dataset_version_number=1...

100%|██████████| 5.48M/5.48M [00:00<00:00, 16.9MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/prepinstaprime/black-friday-sales-data/versions/1

###Checking weather data is loaded using head function

In [5]:
import pandas as pd

df=pd.read_csv('/root/.cache/kagglehub/datasets/prepinstaprime/black-friday-sales-data/versions/1/train.csv')
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

###Filtering the DataFrame to find all purchases with a value higher than $15,000

In [7]:
high_value_purchases = df[df['Purchase'] > 15000]
print(high_value_purchases)

        User_ID Product_ID Gender    Age  Occupation City_Category  \
1       1000001  P00248942      F   0-17          10             A
5       1000003  P00193542      M  26-35          15             A
6       1000004  P00184942      M  46-50           7             B
7       1000004  P00346142      M  46-50           7             B
8       1000004   P0097242      M  46-50           7             B
...         ...        ...    ...    ...         ...           ...
545864  1006036  P00111042      F  26-35          15             B
545865  1006036  P00152142      F  26-35          15             B
545882  1006036  P00270542      F  26-35          15             B
545904  1006040  P00081142      M  26-35           6             B
545908  1006040  P00127642      M  26-35           6             B

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                               2               0                   1
5                               3               0                   1
6                               2               1                   1
7                               2               1                   1
8                               2               1                   1
...                           ...             ...                 ...
545864                         4+               1                  15
545865                         4+               1                   7
545882                         4+               1                   1
545904                          2               0                   6
545908                          2               0                   1

        Product_Category_2  Product_Category_3  Purchase
1                      6.0                14.0     15200
5                      2.0                 NaN     15227
6                      8.0                17.0     19215
7                     15.0                 NaN     15854
8                     16.0                 NaN     15686
...                    ...                 ...       ...
545864                 NaN                 NaN     21390
545865                 NaN                 NaN     16586
545882                 6.0                 8.0     15653
545904                 8.0                14.0     16493
545908                 2.0                15.0     15694

[110523 rows x 12 columns]

###Combine multiple conditions to find a specific customer segment
###Then apply all conditions simultaneously using the '**&**' operator

In [12]:
condition1 = df['Gender'] == 'F'
condition2 = df['City_Category'] == 'A'
condition3 = df['Age'] == '0-17'

target_segment = df[condition1 & condition2 & condition3]
display(target_segment)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
3010,1000484,P00321942,F,0-17,10,A,2,0,5,NaN,NaN,5357
...,...,...,...,...,...,...,...,...,...,...,...,...
546889,1001434,P00375436,F,0-17,10,A,0,0,20,NaN,NaN,475
547498,1002346,P00370293,F,0-17,10,A,1,0,19,NaN,NaN,49
548202,1003382,P00372445,F,0-17,10,A,2,0,20,NaN,NaN,491
548982,1004493,P00372445,F,0-17,10,A,1,0,20,NaN,NaN,374
549562,1005302,P00372445,F,0-17,10,A,1,0,20,NaN,NaN,139