### **1. Import required modules (files from google.colab and pandas)**
### **2. Upload the file**
### **3. printing the uploaded file's name**

In [19]:
from google.colab import files
import pandas as pd

uploaded = files.upload()
Titanic = list(uploaded.keys())[0]

print(f"File '{Titanic}' uploaded successfully.")

Saving test.csv to test (1).csv
File 'test (1).csv' uploaded successfully.

### **Load the data from the file into a pandas DataFrame using**
### **exception hadling to avoide error**

In [20]:
try:
    df = pd.read_csv(Titanic)
    print("Data loaded into a pandas DataFrame:")
    display(df.head())
except Exception as e:
    print(f"Error loading data: {e}")

Data loaded into a pandas DataFrame:

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

### **Inspecting dataset for Empty/Null values**

In [21]:
df.isnull()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
413,False,False,False,False,True,False,False,False,False,True,False
414,False,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,True,False
416,False,False,False,False,True,False,False,False,False,True,False
417,False,False,False,False,True,False,False,False,False,True,False

### **Empty values based on Columns**

In [22]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

### **Total no. of empty values in dataset**

In [23]:
df.isnull().sum().sum()

np.int64(414)

### **Handling missing values in the dataset**
1. Removing the column that contains too many missing values
2. Filling Age & Fare column with mean of values/entries
3. Print the result after handling the empty/null values

In [29]:
#df = df.drop('Cabin', axis=1)
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())
print("Missing values after handling:\n",df.isnull().sum())

Missing values after handling:
 PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64